// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: AQ_PC_style

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void HideAqi_Animation( lv_obj_t *TargetObject, int delay);
void ShowAqi_Animation( lv_obj_t *TargetObject, int delay);
void LoadingAnim_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_LoadingScreen
void ui_LoadingScreen_screen_init(void);
void ui_event_LoadingScreen( lv_event_t * e);
lv_obj_t *ui_LoadingScreen;
lv_obj_t *ui_Logo;
lv_obj_t *ui_LoadingBar;
lv_obj_t *ui_LoadingStatusLabel;
lv_obj_t *ui_LoaderInd1;
lv_obj_t *ui_LoaderInd2;
lv_obj_t *ui_LoaderInd3;


// SCREEN: ui_DataScreen
void ui_DataScreen_screen_init(void);
lv_obj_t *ui_DataScreen;
lv_obj_t *ui_Wallpaper;
lv_obj_t *ui_Data;
lv_obj_t *ui_Container1;
lv_obj_t *ui_MinimalHumidityArc;
lv_obj_t *ui_MinimalTemperatureArc;
lv_obj_t *ui_MinimalTemperatureValueLabel;
lv_obj_t *ui_MinimalHumidityValueLabel;
lv_obj_t *ui_Container2;
lv_obj_t *ui_MinimalEco2Label;
lv_obj_t *ui_MinimalTvocLabel;
lv_obj_t *ui_MinimalTvocArc;
lv_obj_t *ui_MinimalEcoArc;
lv_obj_t *ui_Button1;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_loader_ind__[1] = {&ui_img_loader_ind__1_png};
const lv_img_dsc_t *ui_imgset_loader_ind_[2] = {&ui_img_loader_ind_2_png, &ui_img_loader_ind_3_png};
const lv_img_dsc_t *ui_imgset_retroboxicon[1] = {&ui_img_retroboxicon1_png};
const lv_img_dsc_t *ui_imgset_datascreen_420_[1] = {&ui_img_datascreen_420_320_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void HideAqi_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, -320 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}
void ShowAqi_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 1000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, -320, 0 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_in_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}
void LoadingAnim_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 2465);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, 85 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, LV_ANIM_REPEAT_INFINITE );
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_LoadingScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      LoadingAnim_Animation(ui_LoaderInd2, 261);
      LoadingAnim_Animation(ui_LoaderInd3, 0);
      LoadingAnim_Animation(ui_LoaderInd1, 522);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_DataScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_DataScreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_LoadingScreen_screen_init();
ui_DataScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_LoadingScreen);
}
