// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AQ_PC_v4

#ifndef _AQ_PC_V4_UI_H
#define _AQ_PC_V4_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_LoadingScreen.h"
#include "ui_HomeScreen.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * LoadingBar1BoxAnimation_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * LoadingBar2BoxAnimation_Animation( lv_obj_t *TargetObject, int delay);
extern lv_anim_t * LoadingBar3BoxAnimation_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_loadingscreenframe_png);   // assets/LoadingScreenFrame.png
LV_IMG_DECLARE( ui_img_loadingbox1_png);   // assets/LoadingBox1.png
LV_IMG_DECLARE( ui_img_loadingbox2_png);   // assets/LoadingBox2.png
LV_IMG_DECLARE( ui_img_loadingbox3_png);   // assets/LoadingBox3.png
LV_IMG_DECLARE( ui_img_main_app_frame_png);   // assets/Main_App_Frame.png
LV_IMG_DECLARE( ui_img_homeframe_png);   // assets/HomeFrame.png
LV_IMG_DECLARE( ui_img_nextbutton_active_png);   // assets/NextButton_Active.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
