// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: AQ_PC

#ifndef UI_DATETIMESCREEN_H
#define UI_DATETIMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DateTimeScreen
extern void ui_DateTimeScreen_screen_init(void);
extern void ui_DateTimeScreen_screen_destroy(void);
extern lv_obj_t *ui_DateTimeScreen;
extern lv_obj_t *ui_DateTimeScreenBg;
extern lv_obj_t *ui_DateTimeScreenMainAppFrame;
extern lv_obj_t *ui_DateTimeScreenMainAppImg;
extern lv_obj_t *ui_DateTimeScreenTabs;
extern lv_obj_t *ui_DateTimeScreenHomeTab;
extern lv_obj_t *ui_DateTimeScreenSettingsTab;
extern lv_obj_t *ui_DateTimeScreenDateTimeTab;
extern lv_obj_t *ui_DateTimeScreenMonthLabel;
extern lv_obj_t *ui_DateTimeScreenYearLabel;
extern lv_obj_t *ui_DateTimeScreenButtons;
extern lv_obj_t *ui_DateTimeScreenNextButton;
extern void ui_event_DateTimeScreenPreviousButton( lv_event_t * e);
extern lv_obj_t *ui_DateTimeScreenPreviousButton;
extern lv_obj_t *ui_DateTimeScreenTimeLabel;
extern lv_obj_t *ui_HoursContainer;
extern lv_obj_t *ui_MinuteArrow;
extern lv_obj_t *ui_HourArrow;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

