// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: AQ_PC

#include "ui.h"

lv_obj_t *ui_DateTimeScreen = NULL;lv_obj_t *ui_DateTimeScreenBg = NULL;lv_obj_t *ui_DateTimeScreenMainAppFrame = NULL;lv_obj_t *ui_DateTimeScreenMainAppImg = NULL;lv_obj_t *ui_DateTimeScreenTabs = NULL;lv_obj_t *ui_DateTimeScreenHomeTab = NULL;lv_obj_t *ui_DateTimeScreenSettingsTab = NULL;lv_obj_t *ui_DateTimeScreenDateTimeTab = NULL;lv_obj_t *ui_DateTimeScreenMonthLabel = NULL;lv_obj_t *ui_DateTimeScreenYearLabel = NULL;lv_obj_t *ui_DateTimeScreenButtons = NULL;lv_obj_t *ui_DateTimeScreenNextButton = NULL;lv_obj_t *ui_DateTimeScreenPreviousButton = NULL;lv_obj_t *ui_DateTimeScreenTimeLabel = NULL;lv_obj_t *ui_HoursContainer = NULL;lv_obj_t *ui_MinuteArrow = NULL;lv_obj_t *ui_HourArrow = NULL;
// event funtions
void ui_event_DateTimeScreenPreviousButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_TempHumScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_TempHumScreen_screen_init);
}
}

// build funtions

void ui_DateTimeScreen_screen_init(void)
{
ui_DateTimeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_DateTimeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DateTimeScreenBg = lv_img_create(ui_DateTimeScreen);
lv_img_set_src(ui_DateTimeScreenBg, &ui_img_default_screen_png);
lv_obj_set_width( ui_DateTimeScreenBg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateTimeScreenBg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DateTimeScreenBg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DateTimeScreenBg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DateTimeScreenBg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DateTimeScreenMainAppFrame = lv_obj_create(ui_DateTimeScreen);
lv_obj_remove_style_all(ui_DateTimeScreenMainAppFrame);
lv_obj_set_width( ui_DateTimeScreenMainAppFrame, 303);
lv_obj_set_height( ui_DateTimeScreenMainAppFrame, 217);
lv_obj_set_x( ui_DateTimeScreenMainAppFrame, 0 );
lv_obj_set_y( ui_DateTimeScreenMainAppFrame, -9 );
lv_obj_set_align( ui_DateTimeScreenMainAppFrame, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_DateTimeScreenMainAppFrame, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DateTimeScreenMainAppImg = lv_img_create(ui_DateTimeScreenMainAppFrame);
lv_img_set_src(ui_DateTimeScreenMainAppImg, &ui_img_datetimescreenmainframe_png);
lv_obj_set_width( ui_DateTimeScreenMainAppImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateTimeScreenMainAppImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DateTimeScreenMainAppImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DateTimeScreenMainAppImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DateTimeScreenMainAppImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DateTimeScreenTabs = lv_obj_create(ui_DateTimeScreenMainAppFrame);
lv_obj_remove_style_all(ui_DateTimeScreenTabs);
lv_obj_set_width( ui_DateTimeScreenTabs, 219);
lv_obj_set_height( ui_DateTimeScreenTabs, 16);
lv_obj_set_x( ui_DateTimeScreenTabs, -41 );
lv_obj_set_y( ui_DateTimeScreenTabs, -88 );
lv_obj_set_align( ui_DateTimeScreenTabs, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_DateTimeScreenTabs, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DateTimeScreenHomeTab = lv_img_create(ui_DateTimeScreenTabs);
lv_img_set_src(ui_DateTimeScreenHomeTab, &ui_img_hometabinactive_png);
lv_obj_set_width( ui_DateTimeScreenHomeTab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateTimeScreenHomeTab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DateTimeScreenHomeTab, -83 );
lv_obj_set_y( ui_DateTimeScreenHomeTab, 0 );
lv_obj_set_align( ui_DateTimeScreenHomeTab, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DateTimeScreenHomeTab, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DateTimeScreenHomeTab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DateTimeScreenSettingsTab = lv_img_create(ui_DateTimeScreenTabs);
lv_img_set_src(ui_DateTimeScreenSettingsTab, &ui_img_settingstabinactive_png);
lv_obj_set_width( ui_DateTimeScreenSettingsTab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateTimeScreenSettingsTab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DateTimeScreenSettingsTab, 19 );
lv_obj_set_y( ui_DateTimeScreenSettingsTab, 0 );
lv_obj_set_align( ui_DateTimeScreenSettingsTab, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DateTimeScreenSettingsTab, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DateTimeScreenSettingsTab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DateTimeScreenDateTimeTab = lv_img_create(ui_DateTimeScreenTabs);
lv_img_set_src(ui_DateTimeScreenDateTimeTab, &ui_img_datetimetabactive_png);
lv_obj_set_width( ui_DateTimeScreenDateTimeTab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateTimeScreenDateTimeTab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DateTimeScreenDateTimeTab, -32 );
lv_obj_set_y( ui_DateTimeScreenDateTimeTab, 0 );
lv_obj_set_align( ui_DateTimeScreenDateTimeTab, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DateTimeScreenDateTimeTab, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_DateTimeScreenDateTimeTab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DateTimeScreenMonthLabel = lv_label_create(ui_DateTimeScreenMainAppFrame);
lv_obj_set_width( ui_DateTimeScreenMonthLabel, 53);
lv_obj_set_height( ui_DateTimeScreenMonthLabel, 16);
lv_obj_set_x( ui_DateTimeScreenMonthLabel, -106 );
lv_obj_set_y( ui_DateTimeScreenMonthLabel, -58 );
lv_obj_set_align( ui_DateTimeScreenMonthLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateTimeScreenMonthLabel,"Dec");
lv_obj_set_style_text_align(ui_DateTimeScreenMonthLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DateTimeScreenMonthLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateTimeScreenYearLabel = lv_label_create(ui_DateTimeScreenMainAppFrame);
lv_obj_set_width( ui_DateTimeScreenYearLabel, 53);
lv_obj_set_height( ui_DateTimeScreenYearLabel, 16);
lv_obj_set_x( ui_DateTimeScreenYearLabel, -40 );
lv_obj_set_y( ui_DateTimeScreenYearLabel, -58 );
lv_obj_set_align( ui_DateTimeScreenYearLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateTimeScreenYearLabel,"2025");
lv_obj_set_style_text_align(ui_DateTimeScreenYearLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DateTimeScreenYearLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateTimeScreenButtons = lv_obj_create(ui_DateTimeScreenMainAppFrame);
lv_obj_remove_style_all(ui_DateTimeScreenButtons);
lv_obj_set_width( ui_DateTimeScreenButtons, 258);
lv_obj_set_height( ui_DateTimeScreenButtons, 21);
lv_obj_set_x( ui_DateTimeScreenButtons, 23 );
lv_obj_set_y( ui_DateTimeScreenButtons, 97 );
lv_obj_set_align( ui_DateTimeScreenButtons, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_DateTimeScreenButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_DateTimeScreenNextButton = lv_imgbtn_create(ui_DateTimeScreenButtons);
lv_imgbtn_set_src(ui_DateTimeScreenNextButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nextbuttonactive_png, NULL);
lv_obj_set_width( ui_DateTimeScreenNextButton, 57);
lv_obj_set_height( ui_DateTimeScreenNextButton, 19);
lv_obj_set_x( ui_DateTimeScreenNextButton, 35 );
lv_obj_set_y( ui_DateTimeScreenNextButton, 1 );
lv_obj_set_align( ui_DateTimeScreenNextButton, LV_ALIGN_CENTER );

ui_DateTimeScreenPreviousButton = lv_imgbtn_create(ui_DateTimeScreenButtons);
lv_imgbtn_set_src(ui_DateTimeScreenPreviousButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_previousbuttonactive_png, NULL);
lv_obj_set_width( ui_DateTimeScreenPreviousButton, 57);
lv_obj_set_height( ui_DateTimeScreenPreviousButton, 19);
lv_obj_set_x( ui_DateTimeScreenPreviousButton, -28 );
lv_obj_set_y( ui_DateTimeScreenPreviousButton, 1 );
lv_obj_set_align( ui_DateTimeScreenPreviousButton, LV_ALIGN_CENTER );

ui_DateTimeScreenTimeLabel = lv_label_create(ui_DateTimeScreen);
lv_obj_set_width( ui_DateTimeScreenTimeLabel, 54);
lv_obj_set_height( ui_DateTimeScreenTimeLabel, 16);
lv_obj_set_x( ui_DateTimeScreenTimeLabel, 72 );
lv_obj_set_y( ui_DateTimeScreenTimeLabel, 56 );
lv_obj_set_align( ui_DateTimeScreenTimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateTimeScreenTimeLabel,"8:45:02");
lv_obj_set_style_text_align(ui_DateTimeScreenTimeLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HoursContainer = lv_obj_create(ui_DateTimeScreen);
lv_obj_remove_style_all(ui_HoursContainer);
lv_obj_set_width( ui_HoursContainer, 113);
lv_obj_set_height( ui_HoursContainer, 113);
lv_obj_set_x( ui_HoursContainer, 72 );
lv_obj_set_y( ui_HoursContainer, -16 );
lv_obj_set_align( ui_HoursContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_HoursContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MinuteArrow = lv_img_create(ui_HoursContainer);
lv_img_set_src(ui_MinuteArrow, &ui_img_minutearrow_png);
lv_obj_set_width( ui_MinuteArrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinuteArrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinuteArrow, 0 );
lv_obj_set_y( ui_MinuteArrow, -25 );
lv_obj_set_align( ui_MinuteArrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_MinuteArrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_MinuteArrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_MinuteArrow,4,50);
lv_img_set_angle(ui_MinuteArrow,1);

ui_HourArrow = lv_img_create(ui_HoursContainer);
lv_img_set_src(ui_HourArrow, &ui_img_hourarrow_png);
lv_obj_set_width( ui_HourArrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HourArrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HourArrow, 0 );
lv_obj_set_y( ui_HourArrow, -20 );
lv_obj_set_align( ui_HourArrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HourArrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HourArrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_HourArrow,5,40);
lv_img_set_angle(ui_HourArrow,900);

lv_obj_add_event_cb(ui_DateTimeScreenPreviousButton, ui_event_DateTimeScreenPreviousButton, LV_EVENT_ALL, NULL);

}

void ui_DateTimeScreen_screen_destroy(void)
{
   if (ui_DateTimeScreen) lv_obj_del(ui_DateTimeScreen);

// NULL screen variables
ui_DateTimeScreen= NULL;
ui_DateTimeScreenBg= NULL;
ui_DateTimeScreenMainAppFrame= NULL;
ui_DateTimeScreenMainAppImg= NULL;
ui_DateTimeScreenTabs= NULL;
ui_DateTimeScreenHomeTab= NULL;
ui_DateTimeScreenSettingsTab= NULL;
ui_DateTimeScreenDateTimeTab= NULL;
ui_DateTimeScreenMonthLabel= NULL;
ui_DateTimeScreenYearLabel= NULL;
ui_DateTimeScreenButtons= NULL;
ui_DateTimeScreenNextButton= NULL;
ui_DateTimeScreenPreviousButton= NULL;
ui_DateTimeScreenTimeLabel= NULL;
ui_HoursContainer= NULL;
ui_MinuteArrow= NULL;
ui_HourArrow= NULL;

}
