// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AQ_PC_v4

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t *ui_HomeScreen;
extern lv_obj_t *ui_HomeScreenBackgroundImage;
extern lv_obj_t *ui_HomeScreenTabFrameImage;
extern lv_obj_t *ui_HomeScreenTempLabel;
extern lv_obj_t *ui_HomeScreenHumLabel;
extern lv_obj_t *ui_HomeScreenAQLabel;
extern lv_obj_t *ui_HomeScreenHumLabel1;
extern lv_obj_t *ui_HomeScreenNextButtonImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

