// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AQ_PC_v4

#include "ui.h"

lv_obj_t *ui_HomeScreen = NULL;lv_obj_t *ui_HomeScreenBackgroundImage = NULL;lv_obj_t *ui_HomeScreenTabFrameImage = NULL;lv_obj_t *ui_HomeScreenTempLabel = NULL;lv_obj_t *ui_HomeScreenHumLabel = NULL;lv_obj_t *ui_HomeScreenAQLabel = NULL;lv_obj_t *ui_HomeScreenHumLabel1 = NULL;lv_obj_t *ui_HomeScreenNextButtonImage = NULL;
// event funtions

// build funtions

void ui_HomeScreen_screen_init(void)
{
ui_HomeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeScreenBackgroundImage = lv_img_create(ui_HomeScreen);
lv_img_set_src(ui_HomeScreenBackgroundImage, &ui_img_main_app_frame_png);
lv_obj_set_width( ui_HomeScreenBackgroundImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HomeScreenBackgroundImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_HomeScreenBackgroundImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeScreenBackgroundImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HomeScreenBackgroundImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeScreenTabFrameImage = lv_img_create(ui_HomeScreenBackgroundImage);
lv_img_set_src(ui_HomeScreenTabFrameImage, &ui_img_homeframe_png);
lv_obj_set_width( ui_HomeScreenTabFrameImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HomeScreenTabFrameImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeScreenTabFrameImage, 0 );
lv_obj_set_y( ui_HomeScreenTabFrameImage, -9 );
lv_obj_set_align( ui_HomeScreenTabFrameImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeScreenTabFrameImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HomeScreenTabFrameImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeScreenTempLabel = lv_label_create(ui_HomeScreenTabFrameImage);
lv_obj_set_width( ui_HomeScreenTempLabel, 100);
lv_obj_set_height( ui_HomeScreenTempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeScreenTempLabel, -74 );
lv_obj_set_y( ui_HomeScreenTempLabel, -9 );
lv_obj_set_align( ui_HomeScreenTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeScreenTempLabel,"Test");
lv_obj_set_style_text_align(ui_HomeScreenTempLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HomeScreenTempLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreenHumLabel = lv_label_create(ui_HomeScreenTabFrameImage);
lv_obj_set_width( ui_HomeScreenHumLabel, 100);
lv_obj_set_height( ui_HomeScreenHumLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeScreenHumLabel, -74 );
lv_obj_set_y( ui_HomeScreenHumLabel, 11 );
lv_obj_set_align( ui_HomeScreenHumLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeScreenHumLabel,"Test");
lv_obj_set_style_text_align(ui_HomeScreenHumLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HomeScreenHumLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreenAQLabel = lv_label_create(ui_HomeScreenTabFrameImage);
lv_obj_set_width( ui_HomeScreenAQLabel, 100);
lv_obj_set_height( ui_HomeScreenAQLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeScreenAQLabel, 74 );
lv_obj_set_y( ui_HomeScreenAQLabel, -9 );
lv_obj_set_align( ui_HomeScreenAQLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeScreenAQLabel,"Test");
lv_obj_set_style_text_align(ui_HomeScreenAQLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HomeScreenAQLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreenHumLabel1 = lv_label_create(ui_HomeScreenTabFrameImage);
lv_obj_set_width( ui_HomeScreenHumLabel1, 100);
lv_obj_set_height( ui_HomeScreenHumLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeScreenHumLabel1, 74 );
lv_obj_set_y( ui_HomeScreenHumLabel1, 11 );
lv_obj_set_align( ui_HomeScreenHumLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeScreenHumLabel1,"Test");
lv_obj_set_style_text_align(ui_HomeScreenHumLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HomeScreenHumLabel1, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreenNextButtonImage = lv_img_create(ui_HomeScreenBackgroundImage);
lv_img_set_src(ui_HomeScreenNextButtonImage, &ui_img_nextbutton_active_png);
lv_obj_set_width( ui_HomeScreenNextButtonImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HomeScreenNextButtonImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HomeScreenNextButtonImage, 58 );
lv_obj_set_y( ui_HomeScreenNextButtonImage, 88 );
lv_obj_set_align( ui_HomeScreenNextButtonImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_HomeScreenNextButtonImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_HomeScreenNextButtonImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_HomeScreen_screen_destroy(void)
{
   if (ui_HomeScreen) lv_obj_del(ui_HomeScreen);

// NULL screen variables
ui_HomeScreen= NULL;
ui_HomeScreenBackgroundImage= NULL;
ui_HomeScreenTabFrameImage= NULL;
ui_HomeScreenTempLabel= NULL;
ui_HomeScreenHumLabel= NULL;
ui_HomeScreenAQLabel= NULL;
ui_HomeScreenHumLabel1= NULL;
ui_HomeScreenNextButtonImage= NULL;

}
