// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: AQ_PC

#ifndef UI_LOADINGSCREEN_H
#define UI_LOADINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LoadingScreen
extern void ui_LoadingScreen_screen_init(void);
extern void ui_LoadingScreen_screen_destroy(void);
extern void ui_event_LoadingScreen( lv_event_t * e);
extern lv_obj_t *ui_LoadingScreen;
extern lv_obj_t *ui_LoadingScreenBg;
extern lv_obj_t *ui_LoadingBox1;
extern lv_obj_t *ui_LoadingBox2;
extern lv_obj_t *ui_LoadingBox3;
extern lv_obj_t *ui_LoadingStatusLabel;
extern lv_obj_t *ui_InitialDateTimeSetup;
extern void ui_event_LoadingScreenInitialDateSetupActions( lv_event_t * e);
extern lv_obj_t *ui_LoadingScreenInitialDateSetupActions;
extern lv_obj_t *ui_LoadingScreenInitialSetupImage;
extern lv_obj_t *ui_LoadingScreenInitialSetupYearLabel;
extern lv_obj_t *ui_LoadingScreenInitialSetupMonthLabel;
extern lv_obj_t *ui_LoadingScreenInitialSetupDayLabel;
extern lv_obj_t *ui_LoadingScreenInitialSetupHoursLabel;
extern lv_obj_t *ui_LoadingScreenInitialSetupMinutesLabel;
extern void ui_event_LoadingScreenSwitchToTempHumScreen( lv_event_t * e);
extern lv_obj_t *ui_LoadingScreenSwitchToTempHumScreen;
extern lv_obj_t *ui_InitialNetworkSetup;
extern void ui_event_LoadingScreenInitialNetworkSetupActions( lv_event_t * e);
extern lv_obj_t *ui_LoadingScreenInitialNetworkSetupActions;
extern lv_obj_t *ui_LoadingScreenInitialWifiSetupImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

