// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: AQ_PC_v4

#include "ui.h"

lv_obj_t *ui_LoadingScreen = NULL;lv_obj_t *ui_LoadingStatusLabel = NULL;lv_obj_t *ui_LoadingScreenFrame = NULL;lv_obj_t *ui_LoadingBox1 = NULL;lv_obj_t *ui_LoadingBox2 = NULL;lv_obj_t *ui_LoadingBox3 = NULL;
// event funtions
void ui_event_LoadingScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      LoadingBar3BoxAnimation_Animation(ui_LoadingBox3, 0);
      LoadingBar2BoxAnimation_Animation(ui_LoadingBox2, 0);
      LoadingBar1BoxAnimation_Animation(ui_LoadingBox1, 0);
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_HomeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_HomeScreen_screen_init);
}
}

// build funtions

void ui_LoadingScreen_screen_init(void)
{
ui_LoadingScreen = lv_obj_create(NULL);
lv_obj_add_state( ui_LoadingScreen, LV_STATE_CHECKED );     /// States
lv_obj_clear_flag( ui_LoadingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LoadingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LoadingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LoadingStatusLabel = lv_label_create(ui_LoadingScreen);
lv_obj_set_width( ui_LoadingStatusLabel, 200);
lv_obj_set_height( ui_LoadingStatusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoadingStatusLabel, 0 );
lv_obj_set_y( ui_LoadingStatusLabel, 93 );
lv_obj_set_align( ui_LoadingStatusLabel, LV_ALIGN_CENTER );
lv_obj_set_style_text_color(ui_LoadingStatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LoadingStatusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LoadingStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_decor(ui_LoadingStatusLabel, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LoadingStatusLabel, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LoadingScreenFrame = lv_img_create(ui_LoadingScreen);
lv_img_set_src(ui_LoadingScreenFrame, &ui_img_loadingscreenframe_png);
lv_obj_set_width( ui_LoadingScreenFrame, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoadingScreenFrame, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LoadingScreenFrame, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LoadingScreenFrame, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LoadingScreenFrame, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LoadingBox1 = lv_img_create(ui_LoadingScreenFrame);
lv_img_set_src(ui_LoadingBox1, &ui_img_loadingbox1_png);
lv_obj_set_width( ui_LoadingBox1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoadingBox1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoadingBox1, -85 );
lv_obj_set_y( ui_LoadingBox1, 63 );
lv_obj_set_align( ui_LoadingBox1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LoadingBox1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LoadingBox1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LoadingBox2 = lv_img_create(ui_LoadingScreenFrame);
lv_img_set_src(ui_LoadingBox2, &ui_img_loadingbox2_png);
lv_obj_set_width( ui_LoadingBox2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoadingBox2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoadingBox2, -85 );
lv_obj_set_y( ui_LoadingBox2, 63 );
lv_obj_set_align( ui_LoadingBox2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LoadingBox2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LoadingBox2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LoadingBox3 = lv_img_create(ui_LoadingScreenFrame);
lv_img_set_src(ui_LoadingBox3, &ui_img_loadingbox3_png);
lv_obj_set_width( ui_LoadingBox3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoadingBox3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoadingBox3, -85 );
lv_obj_set_y( ui_LoadingBox3, 63 );
lv_obj_set_align( ui_LoadingBox3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LoadingBox3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LoadingBox3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_LoadingScreen, ui_event_LoadingScreen, LV_EVENT_ALL, NULL);

}

void ui_LoadingScreen_screen_destroy(void)
{
   if (ui_LoadingScreen) lv_obj_del(ui_LoadingScreen);

// NULL screen variables
ui_LoadingScreen= NULL;
ui_LoadingStatusLabel= NULL;
ui_LoadingScreenFrame= NULL;
ui_LoadingBox1= NULL;
ui_LoadingBox2= NULL;
ui_LoadingBox3= NULL;

}
