// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: AQ_PC

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SettingsScreen
extern void ui_SettingsScreen_screen_init(void);
extern void ui_SettingsScreen_screen_destroy(void);
extern lv_obj_t *ui_SettingsScreen;
extern lv_obj_t *ui_SettingsScreenBg;
extern lv_obj_t *ui_IconsList;
extern lv_obj_t *ui_NetworkIconContainer;
extern lv_obj_t *ui_NetworkIcon;
extern lv_obj_t *ui_AppearanceIconContainer;
extern lv_obj_t *ui_AppearanceIcon;
extern lv_obj_t *ui_DateTimeIconContainer;
extern lv_obj_t *ui_DateTimeIcon;
extern lv_obj_t *ui_SettingsScreenButtons;
extern void ui_event_SettingScreenNextButton( lv_event_t * e);
extern lv_obj_t *ui_SettingScreenNextButton;
extern lv_obj_t *ui_SettingScreenEnterButton;
extern void ui_event_SettingsScreenPreviousButton( lv_event_t * e);
extern lv_obj_t *ui_SettingsScreenPreviousButton;
extern lv_obj_t *ui_SettingsDateTimeSetup;
extern void ui_event_SettingsDateSetupActions( lv_event_t * e);
extern lv_obj_t *ui_SettingsDateSetupActions;
extern lv_obj_t *ui_SettingsDateTimeSetupImage;
extern lv_obj_t *ui_SettingsDateTimeSetupYearLabel;
extern lv_obj_t *ui_SettingsDateTimeSetupMonthLabel;
extern lv_obj_t *ui_SettingsDateTimeSetupDayLabel;
extern lv_obj_t *ui_SettingsDateTimeSetupHoursLabel;
extern lv_obj_t *ui_SettingsDateTimeSetupMinutesLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

