// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: AQ_PC

#include "ui.h"

lv_obj_t *ui_SettingsScreen = NULL;lv_obj_t *ui_SettingsScreenBg = NULL;lv_obj_t *ui_IconsList = NULL;lv_obj_t *ui_NetworkIconContainer = NULL;lv_obj_t *ui_NetworkIcon = NULL;lv_obj_t *ui_AppearanceIconContainer = NULL;lv_obj_t *ui_AppearanceIcon = NULL;lv_obj_t *ui_DateTimeIconContainer = NULL;lv_obj_t *ui_DateTimeIcon = NULL;lv_obj_t *ui_SettingsScreenButtons = NULL;lv_obj_t *ui_SettingScreenNextButton = NULL;lv_obj_t *ui_SettingScreenEnterButton = NULL;lv_obj_t *ui_SettingsScreenPreviousButton = NULL;lv_obj_t *ui_SettingsDateTimeSetup = NULL;lv_obj_t *ui_SettingsDateSetupActions = NULL;lv_obj_t *ui_SettingsDateTimeSetupImage = NULL;lv_obj_t *ui_SettingsDateTimeSetupYearLabel = NULL;lv_obj_t *ui_SettingsDateTimeSetupMonthLabel = NULL;lv_obj_t *ui_SettingsDateTimeSetupDayLabel = NULL;lv_obj_t *ui_SettingsDateTimeSetupHoursLabel = NULL;lv_obj_t *ui_SettingsDateTimeSetupMinutesLabel = NULL;
// event funtions
void ui_event_SettingScreenNextButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_FOCUSED) {
      _ui_basic_set_property(ui_SettingScreenNextButton, _UI_BASIC_PROPERTY_POSITION_X,  35);
}
}

void ui_event_SettingsScreenPreviousButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_DateTimeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DateTimeScreen_screen_init);
}
}

void ui_event_SettingsDateSetupActions( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_FOCUSED) {
      _ui_basic_set_property(ui_InitialDateTimeSetup, _UI_BASIC_PROPERTY_POSITION_X,  0);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_basic_set_property(ui_InitialDateTimeSetup, _UI_BASIC_PROPERTY_POSITION_X,  -480);
}
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
ui_SettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsScreenBg = lv_img_create(ui_SettingsScreen);
lv_img_set_src(ui_SettingsScreenBg, &ui_img_default_screen_png);
lv_obj_set_width( ui_SettingsScreenBg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsScreenBg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsScreenBg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsScreenBg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SettingsScreenBg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_IconsList = lv_obj_create(ui_SettingsScreen);
lv_obj_remove_style_all(ui_IconsList);
lv_obj_set_width( ui_IconsList, 100);
lv_obj_set_height( ui_IconsList, 50);
lv_obj_set_align( ui_IconsList, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_IconsList, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_NetworkIconContainer = lv_obj_create(ui_SettingsScreen);
lv_obj_remove_style_all(ui_NetworkIconContainer);
lv_obj_set_width( ui_NetworkIconContainer, 97);
lv_obj_set_height( ui_NetworkIconContainer, 114);
lv_obj_set_x( ui_NetworkIconContainer, -97 );
lv_obj_set_y( ui_NetworkIconContainer, -10 );
lv_obj_set_align( ui_NetworkIconContainer, LV_ALIGN_CENTER );
lv_obj_add_state( ui_NetworkIconContainer, LV_STATE_FOCUSED );     /// States
lv_obj_clear_flag( ui_NetworkIconContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_NetworkIconContainer, 10, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_color(ui_NetworkIconContainer, lv_color_hex(0x41A3FA), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_NetworkIconContainer, 128, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_NetworkIcon = lv_imgbtn_create(ui_NetworkIconContainer);
lv_imgbtn_set_src(ui_NetworkIcon, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_networkicon_png, NULL);
lv_obj_set_width( ui_NetworkIcon, 80);
lv_obj_set_height( ui_NetworkIcon, 104);
lv_obj_set_align( ui_NetworkIcon, LV_ALIGN_CENTER );

ui_AppearanceIconContainer = lv_obj_create(ui_SettingsScreen);
lv_obj_remove_style_all(ui_AppearanceIconContainer);
lv_obj_set_width( ui_AppearanceIconContainer, 97);
lv_obj_set_height( ui_AppearanceIconContainer, 114);
lv_obj_set_x( ui_AppearanceIconContainer, 0 );
lv_obj_set_y( ui_AppearanceIconContainer, -10 );
lv_obj_set_align( ui_AppearanceIconContainer, LV_ALIGN_CENTER );
lv_obj_add_state( ui_AppearanceIconContainer, LV_STATE_DISABLED );     /// States
lv_obj_clear_flag( ui_AppearanceIconContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_AppearanceIconContainer, 10, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_color(ui_AppearanceIconContainer, lv_color_hex(0x41A3FA), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_AppearanceIconContainer, 128, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_AppearanceIcon = lv_imgbtn_create(ui_AppearanceIconContainer);
lv_imgbtn_set_src(ui_AppearanceIcon, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_appearenceicon_png, NULL);
lv_obj_set_width( ui_AppearanceIcon, 92);
lv_obj_set_height( ui_AppearanceIcon, 104);
lv_obj_set_align( ui_AppearanceIcon, LV_ALIGN_CENTER );

ui_DateTimeIconContainer = lv_obj_create(ui_SettingsScreen);
lv_obj_remove_style_all(ui_DateTimeIconContainer);
lv_obj_set_width( ui_DateTimeIconContainer, 97);
lv_obj_set_height( ui_DateTimeIconContainer, 114);
lv_obj_set_x( ui_DateTimeIconContainer, 97 );
lv_obj_set_y( ui_DateTimeIconContainer, -10 );
lv_obj_set_align( ui_DateTimeIconContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_DateTimeIconContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_DateTimeIconContainer, 10, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_color(ui_DateTimeIconContainer, lv_color_hex(0x41A3FA), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_DateTimeIconContainer, 128, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_DateTimeIcon = lv_imgbtn_create(ui_DateTimeIconContainer);
lv_imgbtn_set_src(ui_DateTimeIcon, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_datetimeicon_png, NULL);
lv_obj_set_width( ui_DateTimeIcon, 84);
lv_obj_set_height( ui_DateTimeIcon, 104);
lv_obj_set_align( ui_DateTimeIcon, LV_ALIGN_CENTER );

ui_SettingsScreenButtons = lv_obj_create(ui_SettingsScreen);
lv_obj_remove_style_all(ui_SettingsScreenButtons);
lv_obj_set_width( ui_SettingsScreenButtons, 258);
lv_obj_set_height( ui_SettingsScreenButtons, 21);
lv_obj_set_x( ui_SettingsScreenButtons, 23 );
lv_obj_set_y( ui_SettingsScreenButtons, 88 );
lv_obj_set_align( ui_SettingsScreenButtons, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SettingsScreenButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingScreenNextButton = lv_imgbtn_create(ui_SettingsScreenButtons);
lv_imgbtn_set_src(ui_SettingScreenNextButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nextbuttonactive_png, NULL);
lv_obj_set_width( ui_SettingScreenNextButton, 57);
lv_obj_set_height( ui_SettingScreenNextButton, 19);
lv_obj_set_x( ui_SettingScreenNextButton, 35 );
lv_obj_set_y( ui_SettingScreenNextButton, 1 );
lv_obj_set_align( ui_SettingScreenNextButton, LV_ALIGN_CENTER );

ui_SettingScreenEnterButton = lv_imgbtn_create(ui_SettingsScreenButtons);
lv_imgbtn_set_src(ui_SettingScreenEnterButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_enterbuttonactive_png, NULL);
lv_obj_set_width( ui_SettingScreenEnterButton, 57);
lv_obj_set_height( ui_SettingScreenEnterButton, 19);
lv_obj_set_x( ui_SettingScreenEnterButton, 98 );
lv_obj_set_y( ui_SettingScreenEnterButton, 1 );
lv_obj_set_align( ui_SettingScreenEnterButton, LV_ALIGN_CENTER );

ui_SettingsScreenPreviousButton = lv_imgbtn_create(ui_SettingsScreenButtons);
lv_imgbtn_set_src(ui_SettingsScreenPreviousButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_previousbuttonactive_png, NULL);
lv_obj_set_width( ui_SettingsScreenPreviousButton, 57);
lv_obj_set_height( ui_SettingsScreenPreviousButton, 19);
lv_obj_set_x( ui_SettingsScreenPreviousButton, -28 );
lv_obj_set_y( ui_SettingsScreenPreviousButton, 1 );
lv_obj_set_align( ui_SettingsScreenPreviousButton, LV_ALIGN_CENTER );

ui_SettingsDateTimeSetup = lv_obj_create(ui_SettingsScreen);
lv_obj_remove_style_all(ui_SettingsDateTimeSetup);
lv_obj_set_width( ui_SettingsDateTimeSetup, 480);
lv_obj_set_height( ui_SettingsDateTimeSetup, 320);
lv_obj_set_x( ui_SettingsDateTimeSetup, -480 );
lv_obj_set_y( ui_SettingsDateTimeSetup, 0 );
lv_obj_set_align( ui_SettingsDateTimeSetup, LV_ALIGN_CENTER );
lv_obj_add_state( ui_SettingsDateTimeSetup, LV_STATE_FOCUSED );     /// States
lv_obj_clear_flag( ui_SettingsDateTimeSetup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsDateSetupActions = lv_btn_create(ui_SettingsDateTimeSetup);
lv_obj_set_width( ui_SettingsDateSetupActions, 100);
lv_obj_set_height( ui_SettingsDateSetupActions, 303);
lv_obj_set_x( ui_SettingsDateSetupActions, -180 );
lv_obj_set_y( ui_SettingsDateSetupActions, -4 );
lv_obj_set_align( ui_SettingsDateSetupActions, LV_ALIGN_CENTER );
lv_obj_add_state( ui_SettingsDateSetupActions, LV_STATE_USER_1 | LV_STATE_USER_3 );     /// States
lv_obj_add_flag( ui_SettingsDateSetupActions, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsDateSetupActions, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingsDateSetupActions, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsDateSetupActions, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_SettingsDateSetupActions, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_SettingsDateSetupActions, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_SettingsDateSetupActions, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SettingsDateSetupActions, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsDateTimeSetupImage = lv_img_create(ui_SettingsDateTimeSetup);
lv_img_set_src(ui_SettingsDateTimeSetupImage, &ui_img_datetimesettings_png);
lv_obj_set_width( ui_SettingsDateTimeSetupImage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsDateTimeSetupImage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsDateTimeSetupImage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsDateTimeSetupImage, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_SettingsDateTimeSetupImage, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsDateTimeSetupYearLabel = lv_label_create(ui_SettingsDateTimeSetup);
lv_obj_set_width( ui_SettingsDateTimeSetupYearLabel, 82);
lv_obj_set_height( ui_SettingsDateTimeSetupYearLabel, 19);
lv_obj_set_x( ui_SettingsDateTimeSetupYearLabel, -101 );
lv_obj_set_y( ui_SettingsDateTimeSetupYearLabel, -6 );
lv_obj_set_align( ui_SettingsDateTimeSetupYearLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsDateTimeSetupYearLabel,"Test");
lv_obj_add_state( ui_SettingsDateTimeSetupYearLabel, LV_STATE_FOCUSED );     /// States
lv_obj_set_style_text_align(ui_SettingsDateTimeSetupYearLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupYearLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SettingsDateTimeSetupYearLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_text_opa(ui_SettingsDateTimeSetupYearLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupYearLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_radius(ui_SettingsDateTimeSetupYearLabel, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_color(ui_SettingsDateTimeSetupYearLabel, lv_color_hex(0x306AC3), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_SettingsDateTimeSetupYearLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_SettingsDateTimeSetupMonthLabel = lv_label_create(ui_SettingsDateTimeSetup);
lv_obj_set_width( ui_SettingsDateTimeSetupMonthLabel, 82);
lv_obj_set_height( ui_SettingsDateTimeSetupMonthLabel, 19);
lv_obj_set_x( ui_SettingsDateTimeSetupMonthLabel, 0 );
lv_obj_set_y( ui_SettingsDateTimeSetupMonthLabel, -6 );
lv_obj_set_align( ui_SettingsDateTimeSetupMonthLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsDateTimeSetupMonthLabel,"Test");
lv_obj_set_style_text_align(ui_SettingsDateTimeSetupMonthLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupMonthLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SettingsDateTimeSetupMonthLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_text_opa(ui_SettingsDateTimeSetupMonthLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupMonthLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_radius(ui_SettingsDateTimeSetupMonthLabel, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_color(ui_SettingsDateTimeSetupMonthLabel, lv_color_hex(0x306AC3), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_SettingsDateTimeSetupMonthLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_SettingsDateTimeSetupDayLabel = lv_label_create(ui_SettingsDateTimeSetup);
lv_obj_set_width( ui_SettingsDateTimeSetupDayLabel, 82);
lv_obj_set_height( ui_SettingsDateTimeSetupDayLabel, 19);
lv_obj_set_x( ui_SettingsDateTimeSetupDayLabel, 101 );
lv_obj_set_y( ui_SettingsDateTimeSetupDayLabel, -6 );
lv_obj_set_align( ui_SettingsDateTimeSetupDayLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsDateTimeSetupDayLabel,"Test");
lv_obj_set_style_text_align(ui_SettingsDateTimeSetupDayLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupDayLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SettingsDateTimeSetupDayLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_text_opa(ui_SettingsDateTimeSetupDayLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupDayLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_radius(ui_SettingsDateTimeSetupDayLabel, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_color(ui_SettingsDateTimeSetupDayLabel, lv_color_hex(0x306AC3), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_SettingsDateTimeSetupDayLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_SettingsDateTimeSetupHoursLabel = lv_label_create(ui_SettingsDateTimeSetup);
lv_obj_set_width( ui_SettingsDateTimeSetupHoursLabel, 82);
lv_obj_set_height( ui_SettingsDateTimeSetupHoursLabel, 19);
lv_obj_set_x( ui_SettingsDateTimeSetupHoursLabel, -51 );
lv_obj_set_y( ui_SettingsDateTimeSetupHoursLabel, 50 );
lv_obj_set_align( ui_SettingsDateTimeSetupHoursLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsDateTimeSetupHoursLabel,"Test");
lv_obj_set_style_text_align(ui_SettingsDateTimeSetupHoursLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupHoursLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SettingsDateTimeSetupHoursLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_text_opa(ui_SettingsDateTimeSetupHoursLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupHoursLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_radius(ui_SettingsDateTimeSetupHoursLabel, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_color(ui_SettingsDateTimeSetupHoursLabel, lv_color_hex(0x306AC3), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_SettingsDateTimeSetupHoursLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

ui_SettingsDateTimeSetupMinutesLabel = lv_label_create(ui_SettingsDateTimeSetup);
lv_obj_set_width( ui_SettingsDateTimeSetupMinutesLabel, 82);
lv_obj_set_height( ui_SettingsDateTimeSetupMinutesLabel, 19);
lv_obj_set_x( ui_SettingsDateTimeSetupMinutesLabel, 51 );
lv_obj_set_y( ui_SettingsDateTimeSetupMinutesLabel, 50 );
lv_obj_set_align( ui_SettingsDateTimeSetupMinutesLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsDateTimeSetupMinutesLabel,"Test");
lv_obj_set_style_text_align(ui_SettingsDateTimeSetupMinutesLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupMinutesLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_SettingsDateTimeSetupMinutesLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_text_opa(ui_SettingsDateTimeSetupMinutesLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_text_font(ui_SettingsDateTimeSetupMinutesLabel, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_radius(ui_SettingsDateTimeSetupMinutesLabel, 2, LV_PART_MAIN| LV_STATE_FOCUSED);
lv_obj_set_style_bg_color(ui_SettingsDateTimeSetupMinutesLabel, lv_color_hex(0x306AC3), LV_PART_MAIN | LV_STATE_FOCUSED );
lv_obj_set_style_bg_opa(ui_SettingsDateTimeSetupMinutesLabel, 255, LV_PART_MAIN| LV_STATE_FOCUSED);

lv_obj_add_event_cb(ui_SettingScreenNextButton, ui_event_SettingScreenNextButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsScreenPreviousButton, ui_event_SettingsScreenPreviousButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SettingsDateSetupActions, ui_event_SettingsDateSetupActions, LV_EVENT_ALL, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
   if (ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

// NULL screen variables
ui_SettingsScreen= NULL;
ui_SettingsScreenBg= NULL;
ui_IconsList= NULL;
ui_NetworkIconContainer= NULL;
ui_NetworkIcon= NULL;
ui_AppearanceIconContainer= NULL;
ui_AppearanceIcon= NULL;
ui_DateTimeIconContainer= NULL;
ui_DateTimeIcon= NULL;
ui_SettingsScreenButtons= NULL;
ui_SettingScreenNextButton= NULL;
ui_SettingScreenEnterButton= NULL;
ui_SettingsScreenPreviousButton= NULL;
ui_SettingsDateTimeSetup= NULL;
ui_SettingsDateSetupActions= NULL;
ui_SettingsDateTimeSetupImage= NULL;
ui_SettingsDateTimeSetupYearLabel= NULL;
ui_SettingsDateTimeSetupMonthLabel= NULL;
ui_SettingsDateTimeSetupDayLabel= NULL;
ui_SettingsDateTimeSetupHoursLabel= NULL;
ui_SettingsDateTimeSetupMinutesLabel= NULL;

}
