// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: AQ_PC

#include "ui.h"

lv_obj_t *ui_TempHumScreen = NULL;lv_obj_t *ui_TempHumScreenBg = NULL;lv_obj_t *ui_TempHumScreenMainAppFrame = NULL;lv_obj_t *ui_TempHumScreenMainAppImg = NULL;lv_obj_t *ui_Tabs = NULL;lv_obj_t *ui_TempHumDateTimeTab = NULL;lv_obj_t *ui_TempHumHomeTab = NULL;lv_obj_t *ui_TempHumSettingsTab = NULL;lv_obj_t *ui_HomeScreenTempLabel = NULL;lv_obj_t *ui_HomeScreenHumLabel = NULL;lv_obj_t *ui_TvocLabel = NULL;lv_obj_t *ui_Eco2Label = NULL;lv_obj_t *ui_Buttons = NULL;lv_obj_t *ui_TempHumNextButton = NULL;lv_obj_t *ui_TemperatureArc = NULL;lv_obj_t *ui_HumidityArc = NULL;lv_obj_t *ui_TvocArc = NULL;lv_obj_t *ui_EcoArc = NULL;
// event funtions
void ui_event_TempHumNextButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_DateTimeScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_DateTimeScreen_screen_init);
}
}

// build funtions

void ui_TempHumScreen_screen_init(void)
{
ui_TempHumScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_TempHumScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempHumScreenBg = lv_img_create(ui_TempHumScreen);
lv_img_set_src(ui_TempHumScreenBg, &ui_img_default_screen_png);
lv_obj_set_width( ui_TempHumScreenBg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempHumScreenBg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TempHumScreenBg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TempHumScreenBg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TempHumScreenBg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempHumScreenMainAppFrame = lv_obj_create(ui_TempHumScreen);
lv_obj_remove_style_all(ui_TempHumScreenMainAppFrame);
lv_obj_set_width( ui_TempHumScreenMainAppFrame, 303);
lv_obj_set_height( ui_TempHumScreenMainAppFrame, 217);
lv_obj_set_x( ui_TempHumScreenMainAppFrame, 0 );
lv_obj_set_y( ui_TempHumScreenMainAppFrame, -9 );
lv_obj_set_align( ui_TempHumScreenMainAppFrame, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TempHumScreenMainAppFrame, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempHumScreenMainAppImg = lv_img_create(ui_TempHumScreenMainAppFrame);
lv_img_set_src(ui_TempHumScreenMainAppImg, &ui_img_temphummainframe_png);
lv_obj_set_width( ui_TempHumScreenMainAppImg, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempHumScreenMainAppImg, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_TempHumScreenMainAppImg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TempHumScreenMainAppImg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TempHumScreenMainAppImg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Tabs = lv_obj_create(ui_TempHumScreenMainAppFrame);
lv_obj_remove_style_all(ui_Tabs);
lv_obj_set_width( ui_Tabs, 219);
lv_obj_set_height( ui_Tabs, 16);
lv_obj_set_x( ui_Tabs, -41 );
lv_obj_set_y( ui_Tabs, -88 );
lv_obj_set_align( ui_Tabs, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Tabs, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempHumDateTimeTab = lv_img_create(ui_Tabs);
lv_img_set_src(ui_TempHumDateTimeTab, &ui_img_datetimetabinactive_png);
lv_obj_set_width( ui_TempHumDateTimeTab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempHumDateTimeTab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempHumDateTimeTab, -32 );
lv_obj_set_y( ui_TempHumDateTimeTab, 0 );
lv_obj_set_align( ui_TempHumDateTimeTab, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TempHumDateTimeTab, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TempHumDateTimeTab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempHumHomeTab = lv_img_create(ui_Tabs);
lv_img_set_src(ui_TempHumHomeTab, &ui_img_hometabactive_png);
lv_obj_set_width( ui_TempHumHomeTab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempHumHomeTab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempHumHomeTab, -83 );
lv_obj_set_y( ui_TempHumHomeTab, -1 );
lv_obj_set_align( ui_TempHumHomeTab, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TempHumHomeTab, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TempHumHomeTab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempHumSettingsTab = lv_img_create(ui_Tabs);
lv_img_set_src(ui_TempHumSettingsTab, &ui_img_settingstabinactive_png);
lv_obj_set_width( ui_TempHumSettingsTab, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempHumSettingsTab, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempHumSettingsTab, 19 );
lv_obj_set_y( ui_TempHumSettingsTab, 0 );
lv_obj_set_align( ui_TempHumSettingsTab, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_TempHumSettingsTab, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_TempHumSettingsTab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomeScreenTempLabel = lv_label_create(ui_TempHumScreenMainAppFrame);
lv_obj_set_width( ui_HomeScreenTempLabel, 132);
lv_obj_set_height( ui_HomeScreenTempLabel, 16);
lv_obj_set_x( ui_HomeScreenTempLabel, -73 );
lv_obj_set_y( ui_HomeScreenTempLabel, -11 );
lv_obj_set_align( ui_HomeScreenTempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeScreenTempLabel,"");
lv_obj_set_style_text_align(ui_HomeScreenTempLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HomeScreenHumLabel = lv_label_create(ui_TempHumScreenMainAppFrame);
lv_obj_set_width( ui_HomeScreenHumLabel, 132);
lv_obj_set_height( ui_HomeScreenHumLabel, 16);
lv_obj_set_x( ui_HomeScreenHumLabel, -73 );
lv_obj_set_y( ui_HomeScreenHumLabel, 14 );
lv_obj_set_align( ui_HomeScreenHumLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HomeScreenHumLabel,"");
lv_obj_set_style_text_align(ui_HomeScreenHumLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TvocLabel = lv_label_create(ui_TempHumScreenMainAppFrame);
lv_obj_set_width( ui_TvocLabel, 132);
lv_obj_set_height( ui_TvocLabel, 16);
lv_obj_set_x( ui_TvocLabel, 73 );
lv_obj_set_y( ui_TvocLabel, -11 );
lv_obj_set_align( ui_TvocLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TvocLabel,"");
lv_obj_set_style_text_align(ui_TvocLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Eco2Label = lv_label_create(ui_TempHumScreenMainAppFrame);
lv_obj_set_width( ui_Eco2Label, 132);
lv_obj_set_height( ui_Eco2Label, 16);
lv_obj_set_x( ui_Eco2Label, 73 );
lv_obj_set_y( ui_Eco2Label, 14 );
lv_obj_set_align( ui_Eco2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_Eco2Label,"");
lv_obj_set_style_text_align(ui_Eco2Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttons = lv_obj_create(ui_TempHumScreenMainAppFrame);
lv_obj_remove_style_all(ui_Buttons);
lv_obj_set_width( ui_Buttons, 258);
lv_obj_set_height( ui_Buttons, 21);
lv_obj_set_x( ui_Buttons, 23 );
lv_obj_set_y( ui_Buttons, 97 );
lv_obj_set_align( ui_Buttons, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Buttons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TempHumNextButton = lv_imgbtn_create(ui_Buttons);
lv_imgbtn_set_src(ui_TempHumNextButton, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_nextbuttonactive_png, NULL);
lv_obj_set_width( ui_TempHumNextButton, 57);
lv_obj_set_height( ui_TempHumNextButton, 19);
lv_obj_set_x( ui_TempHumNextButton, 35 );
lv_obj_set_y( ui_TempHumNextButton, 1 );
lv_obj_set_align( ui_TempHumNextButton, LV_ALIGN_CENTER );

ui_TemperatureArc = lv_arc_create(ui_TempHumScreen);
lv_obj_set_width( ui_TemperatureArc, 132);
lv_obj_set_height( ui_TemperatureArc, 130);
lv_obj_set_x( ui_TemperatureArc, -72 );
lv_obj_set_y( ui_TemperatureArc, -8 );
lv_obj_set_align( ui_TemperatureArc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_TemperatureArc, -1000,5000);
lv_arc_set_value(ui_TemperatureArc, 2000);
lv_arc_set_bg_angles(ui_TemperatureArc,4,176);
lv_arc_set_rotation(ui_TemperatureArc,90);
lv_obj_set_style_arc_color(ui_TemperatureArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TemperatureArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TemperatureArc, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_TemperatureArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_TemperatureArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TemperatureArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TemperatureArc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_TemperatureArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TemperatureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TemperatureArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TemperatureArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TemperatureArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TemperatureArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TemperatureArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TemperatureArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TemperatureArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TemperatureArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_HumidityArc = lv_arc_create(ui_TempHumScreen);
lv_obj_set_width( ui_HumidityArc, 132);
lv_obj_set_height( ui_HumidityArc, 130);
lv_obj_set_x( ui_HumidityArc, -72 );
lv_obj_set_y( ui_HumidityArc, -8 );
lv_obj_set_align( ui_HumidityArc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_HumidityArc, 0,10000);
lv_arc_set_value(ui_HumidityArc, 5000);
lv_arc_set_bg_angles(ui_HumidityArc,4,176);
lv_arc_set_mode(ui_HumidityArc, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_HumidityArc,270);
lv_obj_set_style_arc_color(ui_HumidityArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumidityArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HumidityArc, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_HumidityArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_HumidityArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumidityArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HumidityArc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_HumidityArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HumidityArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HumidityArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_HumidityArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_HumidityArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_HumidityArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_HumidityArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HumidityArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HumidityArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HumidityArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_TvocArc = lv_arc_create(ui_TempHumScreen);
lv_obj_set_width( ui_TvocArc, 132);
lv_obj_set_height( ui_TvocArc, 130);
lv_obj_set_x( ui_TvocArc, 74 );
lv_obj_set_y( ui_TvocArc, -8 );
lv_obj_set_align( ui_TvocArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_TvocArc, 50);
lv_arc_set_bg_angles(ui_TvocArc,4,176);
lv_arc_set_rotation(ui_TvocArc,90);
lv_obj_set_style_arc_color(ui_TvocArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TvocArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TvocArc, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_TvocArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_TvocArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TvocArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TvocArc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_TvocArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TvocArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TvocArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TvocArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TvocArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TvocArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TvocArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TvocArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TvocArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TvocArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_EcoArc = lv_arc_create(ui_TempHumScreen);
lv_obj_set_width( ui_EcoArc, 132);
lv_obj_set_height( ui_EcoArc, 130);
lv_obj_set_x( ui_EcoArc, 74 );
lv_obj_set_y( ui_EcoArc, -8 );
lv_obj_set_align( ui_EcoArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_EcoArc, 50);
lv_arc_set_bg_angles(ui_EcoArc,4,176);
lv_arc_set_rotation(ui_EcoArc,270);
lv_obj_set_style_arc_color(ui_EcoArc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_EcoArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_EcoArc, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_EcoArc, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_EcoArc, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_EcoArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_EcoArc, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_EcoArc, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_EcoArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_EcoArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_EcoArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_EcoArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_EcoArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_EcoArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_EcoArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_EcoArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_EcoArc, 2, LV_PART_KNOB| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_TempHumNextButton, ui_event_TempHumNextButton, LV_EVENT_ALL, NULL);

}

void ui_TempHumScreen_screen_destroy(void)
{
   if (ui_TempHumScreen) lv_obj_del(ui_TempHumScreen);

// NULL screen variables
ui_TempHumScreen= NULL;
ui_TempHumScreenBg= NULL;
ui_TempHumScreenMainAppFrame= NULL;
ui_TempHumScreenMainAppImg= NULL;
ui_Tabs= NULL;
ui_TempHumDateTimeTab= NULL;
ui_TempHumHomeTab= NULL;
ui_TempHumSettingsTab= NULL;
ui_HomeScreenTempLabel= NULL;
ui_HomeScreenHumLabel= NULL;
ui_TvocLabel= NULL;
ui_Eco2Label= NULL;
ui_Buttons= NULL;
ui_TempHumNextButton= NULL;
ui_TemperatureArc= NULL;
ui_HumidityArc= NULL;
ui_TvocArc= NULL;
ui_EcoArc= NULL;

}
