// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: AQ_PC

#ifndef UI_TEMPHUMSCREEN_H
#define UI_TEMPHUMSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_TempHumScreen
extern void ui_TempHumScreen_screen_init(void);
extern void ui_TempHumScreen_screen_destroy(void);
extern lv_obj_t *ui_TempHumScreen;
extern lv_obj_t *ui_TempHumScreenBg;
extern lv_obj_t *ui_TempHumScreenMainAppFrame;
extern lv_obj_t *ui_TempHumScreenMainAppImg;
extern lv_obj_t *ui_Tabs;
extern lv_obj_t *ui_TempHumDateTimeTab;
extern lv_obj_t *ui_TempHumHomeTab;
extern lv_obj_t *ui_TempHumSettingsTab;
extern lv_obj_t *ui_HomeScreenTempLabel;
extern lv_obj_t *ui_HomeScreenHumLabel;
extern lv_obj_t *ui_TvocLabel;
extern lv_obj_t *ui_Eco2Label;
extern lv_obj_t *ui_Buttons;
extern void ui_event_TempHumNextButton( lv_event_t * e);
extern lv_obj_t *ui_TempHumNextButton;
extern lv_obj_t *ui_TemperatureArc;
extern lv_obj_t *ui_HumidityArc;
extern lv_obj_t *ui_TvocArc;
extern lv_obj_t *ui_EcoArc;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

