// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: AQ_PC_style

#include "../ui.h"

void ui_DataScreen_screen_init(void)
{
ui_DataScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_DataScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Wallpaper = lv_img_create(ui_DataScreen);
lv_img_set_src(ui_Wallpaper, &ui_img_wallpaper_png);
lv_obj_set_width( ui_Wallpaper, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Wallpaper, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Wallpaper, 0 );
lv_obj_set_y( ui_Wallpaper, 3 );
lv_obj_set_align( ui_Wallpaper, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Wallpaper, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Wallpaper, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Data = lv_img_create(ui_Wallpaper);
lv_img_set_src(ui_Data, &ui_img_datascreen_420_320_png);
lv_obj_set_width( ui_Data, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Data, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Data, 0 );
lv_obj_set_y( ui_Data, -18 );
lv_obj_set_align( ui_Data, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Data, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Data, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container1 = lv_obj_create(ui_Data);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 139);
lv_obj_set_height( ui_Container1, 130);
lv_obj_set_x( ui_Container1, -75 );
lv_obj_set_y( ui_Container1, 10 );
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MinimalHumidityArc = lv_arc_create(ui_Container1);
lv_obj_set_width( ui_MinimalHumidityArc, lv_pct(100));
lv_obj_set_height( ui_MinimalHumidityArc, lv_pct(100));
lv_obj_set_x( ui_MinimalHumidityArc, 2 );
lv_obj_set_y( ui_MinimalHumidityArc, 0 );
lv_obj_set_align( ui_MinimalHumidityArc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_MinimalHumidityArc, 0,10000);
lv_arc_set_value(ui_MinimalHumidityArc, 5000);
lv_arc_set_bg_angles(ui_MinimalHumidityArc,190,350);
lv_arc_set_mode(ui_MinimalHumidityArc, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_MinimalHumidityArc,90);
lv_obj_set_style_arc_color(ui_MinimalHumidityArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_MinimalHumidityArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_MinimalHumidityArc, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_MinimalHumidityArc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_MinimalHumidityArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_MinimalHumidityArc, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_MinimalHumidityArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MinimalHumidityArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MinimalHumidityArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MinimalHumidityArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MinimalHumidityArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MinimalHumidityArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MinimalHumidityArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MinimalHumidityArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MinimalHumidityArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MinimalTemperatureArc = lv_arc_create(ui_Container1);
lv_obj_set_width( ui_MinimalTemperatureArc, lv_pct(100));
lv_obj_set_height( ui_MinimalTemperatureArc, lv_pct(100));
lv_obj_set_x( ui_MinimalTemperatureArc, 1 );
lv_obj_set_y( ui_MinimalTemperatureArc, 0 );
lv_obj_set_align( ui_MinimalTemperatureArc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_MinimalTemperatureArc, -2000,6000);
lv_arc_set_value(ui_MinimalTemperatureArc, 2000);
lv_arc_set_bg_angles(ui_MinimalTemperatureArc,190,350);
lv_arc_set_rotation(ui_MinimalTemperatureArc,270);
lv_obj_set_style_arc_color(ui_MinimalTemperatureArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_MinimalTemperatureArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_MinimalTemperatureArc, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_MinimalTemperatureArc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_MinimalTemperatureArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_MinimalTemperatureArc, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_MinimalTemperatureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MinimalTemperatureArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MinimalTemperatureArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MinimalTemperatureArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MinimalTemperatureArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MinimalTemperatureArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MinimalTemperatureArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MinimalTemperatureArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MinimalTemperatureArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MinimalTemperatureValueLabel = lv_label_create(ui_Container1);
lv_obj_set_width( ui_MinimalTemperatureValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinimalTemperatureValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinimalTemperatureValueLabel, 0 );
lv_obj_set_y( ui_MinimalTemperatureValueLabel, -10 );
lv_obj_set_align( ui_MinimalTemperatureValueLabel, LV_ALIGN_CENTER );

ui_MinimalHumidityValueLabel = lv_label_create(ui_Container1);
lv_obj_set_width( ui_MinimalHumidityValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinimalHumidityValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinimalHumidityValueLabel, 0 );
lv_obj_set_y( ui_MinimalHumidityValueLabel, 11 );
lv_obj_set_align( ui_MinimalHumidityValueLabel, LV_ALIGN_CENTER );

ui_Container2 = lv_obj_create(ui_Data);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 133);
lv_obj_set_height( ui_Container2, 136);
lv_obj_set_x( ui_Container2, 75 );
lv_obj_set_y( ui_Container2, 11 );
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_MinimalEco2Label = lv_label_create(ui_Container2);
lv_obj_set_width( ui_MinimalEco2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinimalEco2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinimalEco2Label, 0 );
lv_obj_set_y( ui_MinimalEco2Label, -10 );
lv_obj_set_align( ui_MinimalEco2Label, LV_ALIGN_CENTER );

ui_MinimalTvocLabel = lv_label_create(ui_Container2);
lv_obj_set_width( ui_MinimalTvocLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MinimalTvocLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MinimalTvocLabel, 0 );
lv_obj_set_y( ui_MinimalTvocLabel, 11 );
lv_obj_set_align( ui_MinimalTvocLabel, LV_ALIGN_CENTER );

ui_MinimalTvocArc = lv_arc_create(ui_Container2);
lv_obj_set_width( ui_MinimalTvocArc, 122);
lv_obj_set_height( ui_MinimalTvocArc, 122);
lv_obj_set_align( ui_MinimalTvocArc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_MinimalTvocArc, 0,65000);
lv_arc_set_value(ui_MinimalTvocArc, 75);
lv_arc_set_bg_angles(ui_MinimalTvocArc,190,350);
lv_arc_set_mode(ui_MinimalTvocArc, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_MinimalTvocArc,90);
lv_obj_set_style_arc_color(ui_MinimalTvocArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_MinimalTvocArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_MinimalTvocArc, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_MinimalTvocArc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_MinimalTvocArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_MinimalTvocArc, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_MinimalTvocArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MinimalTvocArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MinimalTvocArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MinimalTvocArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MinimalTvocArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MinimalTvocArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MinimalTvocArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MinimalTvocArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MinimalTvocArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_MinimalEcoArc = lv_arc_create(ui_Container2);
lv_obj_set_width( ui_MinimalEcoArc, 122);
lv_obj_set_height( ui_MinimalEcoArc, 122);
lv_obj_set_align( ui_MinimalEcoArc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_MinimalEcoArc, 400,1500);
lv_arc_set_value(ui_MinimalEcoArc, 2000);
lv_arc_set_bg_angles(ui_MinimalEcoArc,190,350);
lv_arc_set_rotation(ui_MinimalEcoArc,270);
lv_obj_set_style_arc_color(ui_MinimalEcoArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_MinimalEcoArc, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_MinimalEcoArc, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_MinimalEcoArc, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_MinimalEcoArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_MinimalEcoArc, 6, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_MinimalEcoArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MinimalEcoArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_MinimalEcoArc, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_MinimalEcoArc, 255, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_MinimalEcoArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MinimalEcoArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MinimalEcoArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MinimalEcoArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MinimalEcoArc, 1, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Button1 = lv_btn_create(ui_DataScreen);
lv_obj_set_width( ui_Button1, 160);
lv_obj_set_height( ui_Button1, 240);
lv_obj_set_x( ui_Button1, 78 );
lv_obj_set_y( ui_Button1, -2 );
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

}
