// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: AQ_PC_style

#include "../ui.h"

void ui_LoadingScreen_screen_init(void)
{
ui_LoadingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_LoadingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LoadingScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LoadingScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Logo = lv_img_create(ui_LoadingScreen);
lv_img_set_src(ui_Logo, &ui_img_retroboxicon1_png);
lv_obj_set_width( ui_Logo, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Logo, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Logo, 0 );
lv_obj_set_y( ui_Logo, -31 );
lv_obj_set_align( ui_Logo, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Logo, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Logo, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LoadingBar = lv_img_create(ui_LoadingScreen);
lv_img_set_src(ui_LoadingBar, &ui_img_loadingbar_png);
lv_obj_set_width( ui_LoadingBar, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoadingBar, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoadingBar, 0 );
lv_obj_set_y( ui_LoadingBar, 48 );
lv_obj_set_align( ui_LoadingBar, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LoadingBar, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LoadingBar, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LoadingStatusLabel = lv_label_create(ui_LoadingScreen);
lv_obj_set_width( ui_LoadingStatusLabel, 160);
lv_obj_set_height( ui_LoadingStatusLabel, 22);
lv_obj_set_x( ui_LoadingStatusLabel, 0 );
lv_obj_set_y( ui_LoadingStatusLabel, 79 );
lv_obj_set_align( ui_LoadingStatusLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_LoadingStatusLabel,"Loading ...");
lv_obj_set_style_text_color(ui_LoadingStatusLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LoadingStatusLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LoadingStatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LoadingStatusLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LoaderInd1 = lv_img_create(ui_LoadingScreen);
lv_img_set_src(ui_LoaderInd1, &ui_img_loader_ind__1_png);
lv_obj_set_width( ui_LoaderInd1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoaderInd1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoaderInd1, -43 );
lv_obj_set_y( ui_LoaderInd1, 48 );
lv_obj_set_align( ui_LoaderInd1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LoaderInd1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LoaderInd1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LoaderInd2 = lv_img_create(ui_LoadingScreen);
lv_img_set_src(ui_LoaderInd2, &ui_img_loader_ind_2_png);
lv_obj_set_width( ui_LoaderInd2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoaderInd2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoaderInd2, -43 );
lv_obj_set_y( ui_LoaderInd2, 48 );
lv_obj_set_align( ui_LoaderInd2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LoaderInd2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LoaderInd2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LoaderInd3 = lv_img_create(ui_LoadingScreen);
lv_img_set_src(ui_LoaderInd3, &ui_img_loader_ind_3_png);
lv_obj_set_width( ui_LoaderInd3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoaderInd3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoaderInd3, -43 );
lv_obj_set_y( ui_LoaderInd3, 48 );
lv_obj_set_align( ui_LoaderInd3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LoaderInd3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_LoaderInd3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_LoadingScreen, ui_event_LoadingScreen, LV_EVENT_ALL, NULL);

}
