// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image1, &ui_img_roundscreen_png);
lv_obj_set_width( ui_Image1, 240);
lv_obj_set_height( ui_Image1, 240);
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HumidityArc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_HumidityArc, 210);
lv_obj_set_height( ui_HumidityArc, 210);
lv_obj_set_align( ui_HumidityArc, LV_ALIGN_CENTER );
lv_arc_set_value(ui_HumidityArc, 50);
lv_arc_set_bg_angles(ui_HumidityArc,50,130);
lv_arc_set_rotation(ui_HumidityArc,90);
lv_obj_set_style_arc_color(ui_HumidityArc, lv_color_hex(0x207A60), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumidityArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_HumidityArc, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_HumidityArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_HumidityArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_HumidityArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_HumidityArc, lv_color_hex(0x38CDA2), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_HumidityArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_HumidityArc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_HumidityArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HumidityArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_TemperatureArc = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_TemperatureArc, 210);
lv_obj_set_height( ui_TemperatureArc, 210);
lv_obj_set_align( ui_TemperatureArc, LV_ALIGN_CENTER );
lv_arc_set_range(ui_TemperatureArc, -30,50);
lv_arc_set_value(ui_TemperatureArc, 23);
lv_arc_set_bg_angles(ui_TemperatureArc,50,130);
lv_arc_set_mode(ui_TemperatureArc, LV_ARC_MODE_REVERSE);
lv_arc_set_rotation(ui_TemperatureArc,270);
lv_obj_set_style_arc_color(ui_TemperatureArc, lv_color_hex(0x41181E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TemperatureArc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_pad_left(ui_TemperatureArc, 2, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TemperatureArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TemperatureArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TemperatureArc, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_TemperatureArc, lv_color_hex(0xF1474C), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_TemperatureArc, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_TemperatureArc, 8, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_TemperatureArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TemperatureArc, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_HumidityValueLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_HumidityValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HumidityValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HumidityValueLabel, -37 );
lv_obj_set_y( ui_HumidityValueLabel, -56 );
lv_obj_set_align( ui_HumidityValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HumidityValueLabel,"23.2%");
lv_obj_set_style_text_color(ui_HumidityValueLabel, lv_color_hex(0x38CDA2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HumidityValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_HumidityValueLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValueLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_TemperatureValueLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValueLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValueLabel, 38 );
lv_obj_set_y( ui_TemperatureValueLabel, -56 );
lv_obj_set_align( ui_TemperatureValueLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValueLabel,"23.5C");
lv_obj_set_style_text_color(ui_TemperatureValueLabel, lv_color_hex(0xF1474C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValueLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValueLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);

}
